name: Create Release

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: chckout code
        uses: actions/checkout@v2
      - run: ./scripts/travis/compile.sh
      - run: ./scripts/travis/createRpm.sh


